-- MySQL Script generated by MySQL Workbench
-- Sun Nov 14 09:55:26 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema PhonebookDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema PhonebookDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PhonebookDB` DEFAULT CHARACTER SET utf8 ;
USE `PhonebookDB` ;

-- -----------------------------------------------------
-- Table `PhonebookDB`.`Contact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PhonebookDB`.`Contact` (
  `contactID` INT GENERATED ALWAYS AS () STORED,
  `phoneNumber` VARCHAR(45) NOT NULL,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `streetAddress` VARCHAR(90) NULL,
  `town` VARCHAR(90) NULL,
  `birthDate` DATE NULL,
  PRIMARY KEY (`contactID`),
  UNIQUE INDEX `contactID_UNIQUE` (`contactID` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
